import Head from "next/head";
import Body from "../components/Body";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ghar Naksha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Header */}
        <Header />

        {/* Body */}
        <Body />
      </main>
    </div>
  );
}
